### ISSUE TITLE
Seemingly Inconsistent validation

### ISSUE THREAD

**Issue by avishaan** [apigee-127/swagger-tools#109]
If I have `swaggerValidate: true` with the following schema property

``` javascript
        "datetime": {
          "type": "integer",
          "format": "date-time"
        },
```

with the value being passed by the backend equal to:
`2014-12-27T04:33:04.626Z`
I see the following error come up

``` yaml
message:          Response validation failed: failed schema validation
code:             SCHEMA_VALIDATION_FAILED
failedValidation: true
results:
  errors:
    -
      path:
        - datetime
      code:    INVALID_TYPE
      message: Expected type integer but found type string
```

when I do the same with `swaggerValidate: false` It will not have an err being passed in the middleware.

Now, when I have `swaggerValidate: false` with this schema property:

``` javascript
        "datetime": {
          "type": "string",
          "format": "date-time"
        },
```

which I actually expect to be accurate given the output I am getting is `2014-12-27T04:33:04.626Z`
I get the following err passed through the middleware

``` yaml
message:          Parameter (review) failed schema validation
code:             SCHEMA_VALIDATION_FAILED
failedValidation: true
results:
  errors:
    -
      code:    INVALID_TYPE
      message: Expected type string but found type integer
      path:
        - datetime
```

Is this the expected behaviour?
