### ISSUE TITLE
parse parameter integer values

### ISSUE THREAD

**Issue by mohsen1** [apigee-127/swagger-tools#119]
```yaml
   parameters:
      - name: personId
        description: person ID
        in: path
        type: integer
        required: true
```

`req.swagger.params.personId.value` should be a JS number. Currently it's string.
