### ISSUE TITLE
swagger-ui - when declaring path param as global to the path, there is no option to set its value

### ISSUE THREAD

**Issue by borisirota** [apigee-127/swagger-tools#141]
Are you using the last version of swagger-ui ?
I'm not sure if to post this issue in the swagger-ui repo as well :)

* by global to the path I mean to declare the path param like this:
```yaml
  /users/{username}:
    parameters:
      -
        name: username
        in: path
        description: username 
        required: true
        type: string
    get:
        ...
    delete:
        ...
```
and not like this:
```yaml
  /users/{username}:
    get:
        parameters:
          -
            name: username
            in: path
            description: username 
            required: true
            type: string
        ...
    delete:
        parameters:
          -
            name: username
            in: path
            description: username 
            required: true
            type: string
        ...
```

It look like this:
![screen shot 2015-02-05 at 8 29 21 pm](https://cloud.githubusercontent.com/assets/5683472/6066453/ca4d7c8a-ad75-11e4-900f-c9b1ec0ff289.png)

Thanks,
Boris
