### ISSUE TITLE
How to display double decimal point in default value

### ISSUE THREAD

**Issue by Ckim15** [apigee-127/swagger-tools#198]
I have this ProductPrice model whichI need to display default value as  "amount": 0.00, but it displayed as "amount": 0. Any idea to get this work by keep the type as number?

Here is my model implementation: 
```yaml
 ProductPrice:
    properties:
      amount:
        type: number
        format: double
        default: 0.00
```
