### ISSUE TITLE
Critical bug in swagger tools 0.9.1: API operationId already defined

### ISSUE THREAD

**Issue by behrangsa** [apigee-127/swagger-tools#259]
Hi,

In Swagger Tools 0.9.1, a `paths` definition like this breaks apps and prevents them from starting:

```
paths:
  /bar:
    x-swagger-router-controller: bar
    get:
      operationId: index

  /foo:
    x-swagger-router-controller: foo
    get:
      operationId: index
```

This breaks this app with this error:

```
#/paths/~1foo/get/operationId: API operationId already defined: index
```
