### ISSUE TITLE
Optional integer as parameter is not passing swagger validations

### ISSUE THREAD

**Issue by Gargol** [apigee-127/swagger-tools#282]
Whenever integer parameter is defined as so:

```yaml
parameters:
  - name: offset
    required: false
    in: query
    type: integer
    format: int32
```
Even though required is set as `false` validations still throw an error:
```
  swagger-tools:middleware:validator GET /api/myendpoint?offset=&limit= +1ms
  swagger-tools:middleware:validator   Will process: yes +0ms
  swagger-tools:middleware:validator   Request validation: failed +2ms
  swagger-tools:middleware:validator   Reason: Not a valid int32 integer:  +0ms
```

Had to mark the type as `string` and only then it passes through just fine. Is this correct behaviour?
