### ISSUE TITLE
Nested query parameters not parsed

### ISSUE THREAD

**Issue by andyjbas** [apigee-127/swagger-tools#294]
```YAML
# swagger spec
parameters:
  - name: page[limit]
    in: query
    required: false
    type: integer
    format: int32
    default: 10
  - name: page[offset]
    in: query
    required: false
    type: integer
    format: int32
    default: 0
```

It looks like `body-parser` will parse those into something like `{page: {limit: '10', offset: '0'}}` and so [when the value for the param is looked up in swagger tools](https://github.com/apigee-127/swagger-tools/blob/master/middleware/helpers.js#L104) via `req.query[parameter.name]`, it returns nothing. 

I can't find anything in the swagger spec about not supporting this. I am specifically following the [jsonapi specification](http://jsonapi.org/format/#fetching-pagination), which is where my use case comes from.
