### ISSUE TITLE
problem with pattern for collectionFormat: csv

### ISSUE THREAD

**Issue by GiladShoham** [apigee-127/swagger-tools#300]
Hi, 
i have this code:

```yaml
in: query
description: my param.
name: myParam
required: false
type: array
collectionFormat: csv
items:
 type: string
 pattern : myPattern
```

The pattern for this param is not validated.
if i use the same pattern for regular param, for example:
```yaml
in: query
description: my param.
name: myParam
required: false
type: string
pattern : myPattern
```
is working fine and the pattern is validated
