### ISSUE TITLE
Response validation failes with minProperties > 0 when result is JSON.stringified

### ISSUE THREAD

**Issue by deefactorial** [apigee-127/swagger-tools#333]
I'm running into a bug where the response validator is failing when the response is JSON.stringified before being sent and there is a minProperties restriction on the response schema.

the error of the response is:
```
  swagger-tools:middleware:validator   Response validation: +420ms
  swagger-tools:middleware:validator     Response code: 200 +0ms
  swagger-tools:middleware:validator     Validation: failed +1ms
  swagger-tools:middleware:validator   Reason: Number of properties is too few (0 properties), minimum 2 +0ms
```

```yaml
definitions:
  token_response:
    type: object
    minProperties: 2
    required: 
      - access_token
      - expires
    properties:
      access_token:
        type: string
      expires:
        type: string
```

If I remove the JSON.stringified before sending the response the response validates correctly. If I remove the minProperties the response validates correctly.
