### ISSUE TITLE
array enums aren't validated correctly

### ISSUE THREAD

**Issue by snrbrnjna** [apigee-127/swagger-tools#343]
Hi there,

i found a related issue in the [swagger-api](https://github.com/swagger-api/swagger-js/issues/198) repo. There are 2 problems:
1. The enums aren't parsed properly. 
2. The enum validation doesn't work for arrays.

My parameter spec:
```yaml
expand:
    name: expand
    description: 'expand inline links to other resources'
    in: query
    type: array
    items:
      type: string
      enum: ['service', 'thing', 'other']
```
The enum isn't parsed this way. it is only if it is specified this way:
```yaml
expandInSeries:
    name: expand
    description: 'expand inline links to other resources'
    in: query
    type: array
    items:
      type: string
    enum: ['service',  'thing', 'other']
```

[`validateEnum()`](https://github.com/apigee-127/swagger-tools/blob/master/lib/validators.js#L251) should validate not only single values but also enums.
