### ISSUE TITLE
Handling path parameters before calling the path handler.

### ISSUE THREAD

**Issue by Nepoxx** [apigee-127/swagger-tools#344]
From the petstore example:

```yaml
/pets/{pet}:
    get:
      description: Returns a user based on a single ID, if the user does not have access to the pet
      operationId: findPetById
      parameters:
        - name: pet
          in: path
          description: ID of pet to fetch
          required: true
          type: integer
          format: int64
```

Using Express' [`router.param()`](http://expressjs.com/en/api.html#router.param), you could do something like this:

```javascript
router.param('pet', function(req, res, next, id) {

  // try to get the pet details from the Pet model and attach it to the request object
  Pet.find(id, function(err, pet) {
    if (err) {
      next(err);
    } else if (pet) {
      req.pet = pet;
      next();
    } else {
      next(new Error('failed to load pet'));
    }
  });
});
```

This is convenient because your path handlers do not have to do any logic to fetch the pet, either the handler is called and `req.pet` is already set, or it is not called at all.

```javascript
petController.findPetById = (req, res, next) => {
  res.json(req.pet); // req.pet is already set by the router.param above
};
```

Can swagger-tools' router do something similar?
