### ISSUE TITLE
Disallow empty strings

### ISSUE THREAD

**Issue by confuser** [apigee-127/swagger-tools#362]
I know this module is now deprecated but hoping to find an answer with regards to schema validations.

We've just been stung by an issue whereby an empty string passes validation. I can see there is an `allowEmptyValue` option, but it doesn't appear to be usable under definition properties without causing an error to be thrown on start up.

Is it possible force strings through a falsey check, or does this have to be handled at the controller layer instead?

Example definition below:

```yaml
definitions:
  NewLead:
    type: object
    required:
    - first_name
    - last_name
    - initials
    - email
    - address_line_1
    - city
    - postal_code
    - country
    - gender
    properties:
      first_name:
        type: string
      last_name:
        type: string
      initials:
        type: string
      email:
        type: string
      address_line_1:
        type: string
      address_line_2:
        type: string
      city:
        type: string
      state:
        type: string
      postal_code:
        type: string
      country:
        type: string
      source_id:
        type: string
      facebook_id:
        type: string
      gender:
        type: string
        enum:
        - 'male'
        - 'female'
```
