### ISSUE TITLE
Header inconsistency 

### ISSUE THREAD

**Issue by SameerSiddiqui** [apigee-127/swagger-tools#433]
```
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Authorization Token to Validate
          required: true
```

in req.headers.Authorization - gives me undefined- but req.swagger.params.Authorization.value gives me the value...

Why this inconsistency ?

Thanks,
Sameer
