### ISSUE TITLE
client not receiving response

### ISSUE THREAD

**Issue by peacemakr** [apigee-127/swagger-tools#455]
I am using swagger-tools validation middleware and it correctly catches validation errors. Also, it sends it to Express error handler as well. I have made sure the following code gets executed in error handler

```
res.status( 400 ).json( result ).send().flush(); //and different combinations ie. removing send() etc
return;
```
But, client (swagger UI) still does not receive any response.

**Comment by peacemakr** [comment]
fyi: swagger-tools also correctly validates response

```
swagger-tools:middleware:validator   Response validation:
swagger-tools:middleware:validator     Response code: 400
swagger-tools:middleware:validator     Validation: succeeded
```

**Comment by whitlockjc** [comment]
Can you test you API using something other than swagger-ui to see if the response us being sent?  Also, did you look at you browser's console to see if there are any errors?

**Comment by peacemakr** [comment]
browser console (Network Tab) shows the correct 400 response code but no response content

Also, work fine in the browser itself

**Comment by peacemakr** [comment]
I moved the UI to the same domain where API resides and the issue got resolved. However, the response validation started throwing schema validation errors.

/get success response
```
      responses:
        200:
          $ref: '#/responses/ListOK'
```

```
responses:
  ListOK:
    description: 0 or more records in an array (200)
    schema:
      type: array
      items:
        $ref: '#/definitions/Category'
```
```
definitions:
  Category:
    type: object
    minItems: 1   
    properties:
      id:
        type: integer
        format: int64      
        description: category id
      cnt:
        type: integer
        format: int64
        minimum: 0
        description: Count of items under this category        
      name:
        type: string
        description: Display name of category
      description:
        type: string
        description: Details of category
```

When I send an array of objects (or empty array) as response then I get the error 
```
Error: Response validation failed: failed schema validation
```
debug messages:
```
Thu, 01 Dec 2016 01:15:35 GMT swagger-tools:middleware:validator   Response validation:
Thu, 01 Dec 2016 01:15:35 GMT swagger-tools:middleware:validator     Response code: 200
Thu, 01 Dec 2016 01:15:35 GMT swagger-tools:middleware:validator     Validation: failed
Thu, 01 Dec 2016 01:15:35 GMT swagger-tools:middleware:validator   Reason: Failed schema validation
Thu, 01 Dec 2016 01:15:35 GMT swagger-tools:middleware:validator   Errors:
Thu, 01 Dec 2016 01:15:35 GMT swagger-tools:middleware:validator     0:
Thu, 01 Dec 2016 01:15:35 GMT swagger-tools:middleware:validator       code: INVALID_TYPE
Thu, 01 Dec 2016 01:15:35 GMT swagger-tools:middleware:validator       message: Expected type object but found type string
Thu, 01 Dec 2016 01:15:35 GMT swagger-tools:middleware:validator       path: ["0"]
```
When I disable response validation, I get an array of objects without any issues. Example:
```
[{"id":1}]
```
- What is path:["0"]?
- Is anything wrong in my API spec?
