### ISSUE TITLE
Return all validation errors, instead of just the first one

### ISSUE THREAD

**Issue by danielsiwiec** [apigee-127/swagger-tools#469]
It would be very useful, if there was a way to instruct the swagger validator to return all validation errors, instead of just the first occurance. For example:

With a following schema:

```yaml
/search:
  get:
    parameters:
      - name: firstName
        in: query
        required: true
        type: string
      - name: lastName
        in: query
        type: string
        required: true
```

if a call is made to `/search` without any query parameters, I'd like the validator to identify both `firstName` and `lastName` as missing, as opposed to only `firstName`.

Would there be an appetite for such feature? I'd be happy to take a stab at a PR.
