### ISSUE TITLE
Expected type object but found type string

### ISSUE THREAD

**Issue by peacemakr** [apigee-127/swagger-tools#470]
The complete error:
```
#/definitions/Admin/properties/$ref: Expected type object but found type string
```
I have a spec that works fine in Swagger editor ie. not seeing any errors. However, in my node.js program swagger-tools fails to load and throws the error in subject

here is what I have in relevant parts of spec (ignore the indentation):

```
definitions:
 AdminStrict:
    type: object
    required:
      - id
      - ...
    properties:
      id:
        description: ID    
        type: integer
        format: int64
        minimum: 1
   .....
```
then, I have another def using the above:
```
  Admin:
    type: object
    minItems: 2
    required:
      - name
    properties:
      $ref: '#/definitions/AdminStrict/properties'
```

Is something wrong with above? Or, swagger-tools has a bug?
