### ISSUE TITLE
SUGGESTION: Return error code 400 for required path parameter.

### ISSUE THREAD

**Issue by maxcbc** [apigee-127/swagger-tools#489]
Given the following scenario:

```
paths:
  /example/{searchString}:
    get:
      description: "Searches for and retrieves the information for the search string specified."
      parameters:
      - name: "searchString"
        in: "path"
        description: "The string on which to search."
        required: true
        type: "string"
```
if i hit GET: `/example/` without any `searchString` I get a 404.
Given that I dont have a path implemented in my swagger for `/`, this unlikely to be a case of 'NOT FOUND' but more likely an API consumer making a 'BAD REQUEST' to the `/example/{searchString}` endpoint.
As such would it not be better for the validator to return 400 rather than 404 if this is the case?

P.S. If the answer is `submit a PR` that's fine, will put it on my (long) todo list. Just thought i'd raise it as it is a use case that has come up and thought it might be useful for others.
