### ISSUE TITLE
Swagger model properties exclude extra values

### ISSUE THREAD

**Issue by liviuignat** [apigee-127/swagger-tools#503]
Hi guys,

Sorry if this is a duplicate, I did an issue search and didn't find any answer. I multiple scenarios where I am sending data through `body` and reading it from `req.swagger.params.body.value` and I would expect that it read only the properties defined in the model and ignore extra properties.

So for example, if I have a model like the one bellow, I will only get those properties from the body.
```yaml
definitions:
  SomeModel:
    type: object
    required: ['name']
    properties:
      name:
        type: string
        description: The name of the company
      profilePhoto:
        type: string
        description: The profile picture path of the company
```

But actually I will receive everything that I've sent:
```json
 {
  "body": {
    "path": [
      "paths",
      "/user/me",
      "put",
      "parameters",
      "0"
    ],
    "schema": {
      "in": "body",
      "name": "body",
      "description": "The company details to change",
      "schema": {
        "type": "object",
        "required": [
          "name"
        ],
        "properties": {
          "name": {
            "type": "string",
            "description": "The name of the company"
          },
          "profilePhoto": {
            "type": "string",
            "description": "The profile picture path of the company"
          }
        }
      }
    },
    "originalValue": {
      "name": "Liviu Ignat",
      "profilePhoto": "test.jpg",
      "extraProperty": "This property should not be saved"
    },
    "value": {
      "name": "Liviu Ignat",
      "profilePhoto": "test.jpg",
      "extraProperty": "This property should not be saved"
    }
  }
}
```

Is there any feature to "crop" the parameter.value for not defined model properties?  We were using `Joi` that had this feature before and hoping to move everything to swagger models.

Thanks,
Liviu.
