### ISSUE TITLE
Issue with using `discriminator`

### ISSUE THREAD

**Issue by DFaiz** [apigee-127/swagger-tools#590]
Hello,

I'm trying to use `discriminator` but when the validation occurs, it gets the discriminator name, and that's it, I does not get the relevant object.

For example
```
  payment_method:
    type: object
    required:
    - payment_method_type
    discriminator: payment_method_type
    properties:
      payment_method_type:
        type: string
        enum:
        - Crypto
        - CreditCard
```

The schema gets `payment_method_type` as String - for example it equals `Crypto` but it does not get the definition of `Crypto` and compares the request to this object.

Please advise.
